import { Category, Product } from "./types";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "fashion", label: "Fashion & Fabric" },
  { id: "food", label: "Food & Spice" },
  { id: "electronics", label: "Electronics" },
  { id: "beauty", label: "Beauty & Care" },
  { id: "home", label: "Home & Living" },
  { id: "kids", label: "Kids" },
];

export const PRODUCTS: Product[] = [
  {
    id: "fsh-001",
    name: "Ankara Wrapper Set — 2 Yards",
    category: "fashion",
    price: 18500,
    unit: "set",
    description:
      "Vivid wax-print cotton, cut and folded in a matching two-yard set. Colourfast, hand-wash recommended.",
    rating: 4.7,
    reviews: 212,
    stock: 34,
  },
  {
    id: "fsh-002",
    name: "Aso-Oke Gele Headwrap",
    category: "fashion",
    price: 12000,
    unit: "piece",
    description:
      "Hand-woven aso-oke in a stiff finish that holds its shape for owambe and traditional wear.",
    rating: 4.8,
    reviews: 98,
    stock: 21,
  },
  {
    id: "fsh-003",
    name: "Men's Senator Wear — Navy",
    category: "fashion",
    price: 25000,
    unit: "set",
    description:
      "Classic three-piece senator, tailored fit, breathable cotton-blend. True to size.",
    rating: 4.5,
    reviews: 156,
    stock: 15,
  },
  {
    id: "fsh-004",
    name: "ShipFast Tote Bag",
    category: "fashion",
    price: 8500,
    unit: "piece",
    description:
      "Indigo-dyed shipfast cloth over a reinforced canvas base, leather-look straps.",
    rating: 4.6,
    reviews: 64,
    stock: 40,
  },
  {
    id: "food-001",
    name: "Ofada Rice — 5kg",
    category: "food",
    price: 9800,
    unit: "5kg bag",
    description:
      "Locally grown, stone-free Ofada rice, cleaned and bagged. Pairs best with ayamase.",
    rating: 4.9,
    reviews: 340,
    stock: 60,
  },
  {
    id: "food-002",
    name: "Suya Pepper Mix (Yaji)",
    category: "food",
    price: 3200,
    unit: "250g",
    description:
      "Roasted groundnut and pepper blend, ready to season beef, chicken or plantain.",
    rating: 4.8,
    reviews: 288,
    stock: 75,
  },
  {
    id: "food-003",
    name: "Garri (Ijebu) — 4kg",
    category: "food",
    price: 4500,
    unit: "4kg bag",
    description: "Fine-sifted, sour Ijebu garri, sun-dried and sealed fresh.",
    rating: 4.7,
    reviews: 190,
    stock: 90,
  },
  {
    id: "food-004",
    name: "Jollof Spice Blend",
    category: "food",
    price: 2800,
    unit: "200g",
    description:
      "House blend of thyme, curry, chilli and stock cubes — the shortcut to party jollof.",
    rating: 4.6,
    reviews: 142,
    stock: 100,
  },
  {
    id: "food-005",
    name: "Palm Oil — 2L",
    category: "food",
    price: 6200,
    unit: "2L bottle",
    description: "Unbleached, cold-pressed palm oil from Cross River smallholders.",
    rating: 4.5,
    reviews: 88,
    stock: 50,
  },
  {
    id: "elc-001",
    name: "Tecno Spark 20 Smartphone",
    category: "electronics",
    price: 185000,
    unit: "unit",
    description:
      "6.6\" display, 128GB storage, dual SIM. Ships with charger and one-year warranty card.",
    rating: 4.4,
    reviews: 421,
    stock: 12,
  },
  {
    id: "elc-002",
    name: "Infinix Power Bank 20000mAh",
    category: "electronics",
    price: 14500,
    unit: "unit",
    description: "Dual USB output, fast charge, digital percentage display.",
    rating: 4.5,
    reviews: 267,
    stock: 45,
  },
  {
    id: "elc-003",
    name: "Bluetooth Neckband Earphones",
    category: "electronics",
    price: 9900,
    unit: "unit",
    description: "12-hour battery, magnetic buds, sweat resistant for commutes and gym.",
    rating: 4.3,
    reviews: 175,
    stock: 58,
  },
  {
    id: "elc-004",
    name: "LED Rechargeable Lantern",
    category: "electronics",
    price: 11300,
    unit: "unit",
    description: "Built-in power bank function, 3 brightness modes, for the next NEPA outage.",
    rating: 4.6,
    reviews: 203,
    stock: 33,
  },
  {
    id: "bty-001",
    name: "Raw Shea Butter — 500g",
    category: "beauty",
    price: 4200,
    unit: "500g tub",
    description: "Unrefined ivory shea butter, cold-processed in Katsina.",
    rating: 4.8,
    reviews: 310,
    stock: 70,
  },
  {
    id: "bty-002",
    name: "African Black Soap Bar",
    category: "beauty",
    price: 2500,
    unit: "bar",
    description: "Traditional dudu-osun style soap with shea butter and camwood.",
    rating: 4.7,
    reviews: 254,
    stock: 90,
  },
  {
    id: "bty-003",
    name: "Coconut & Aloe Hair Cream",
    category: "beauty",
    price: 5600,
    unit: "300ml",
    description: "Leave-in cream for coily and curly textures, no mineral oil.",
    rating: 4.5,
    reviews: 132,
    stock: 47,
  },
  {
    id: "hm-001",
    name: "Woven Raffia Basket Set",
    category: "home",
    price: 13400,
    unit: "set of 3",
    description: "Hand-woven storage baskets in three sizes, natural raffia finish.",
    rating: 4.6,
    reviews: 76,
    stock: 26,
  },
  {
    id: "hm-002",
    name: "ShipFast Throw Pillow Covers",
    category: "home",
    price: 9200,
    unit: "set of 2",
    description: "45x45cm indigo shipfast covers, hidden zip, insert not included.",
    rating: 4.7,
    reviews: 61,
    stock: 38,
  },
  {
    id: "kid-001",
    name: "Kids Ankara Romper",
    category: "kids",
    price: 7800,
    unit: "piece",
    description: "Soft cotton-ankara blend romper, ages 6 months to 2 years, snap closures.",
    rating: 4.6,
    reviews: 54,
    stock: 30,
  },
  {
    id: "kid-002",
    name: "Educational Alphabet Flash Cards",
    category: "kids",
    price: 3500,
    unit: "set of 26",
    description: "Durable laminated cards with Nigerian-context illustrations, ages 3+.",
    rating: 4.8,
    reviews: 41,
    stock: 65,
  },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsByCategory(category: Category | "all"): Product[] {
  if (category === "all") return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
